# Generated by Django 2.1.3 on 2018-11-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=100)),
                ('voucher', models.FileField(max_length=250, null=True, upload_to='storage/images/')),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
    ]
